# Generated by Django 2.1.7 on 2019-03-11 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Organizations', to='survey.Organization'),
            preserve_default=False,
        ),
    ]
