# Generated by Django 2.1.7 on 2019-03-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20190313_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='code',
            field=models.CharField(default='uqjhReegulmOFroGLq5L', max_length=20, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='code',
            field=models.CharField(default='oaQQxdSXP04gphsytKiQ', max_length=20, verbose_name='code'),
        ),
    ]
