# Generated by Django 2.1.7 on 2019-03-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20190313_1756'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='question',
            name='group',
        ),
        migrations.AlterUniqueTogether(
            name='questiongroup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='questiongroup',
            name='survey',
        ),
        migrations.AlterUniqueTogether(
            name='surveyanswer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='survey',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionGroup',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='SurveyAnswer',
        ),
    ]
